// Generated by scripts/codegen.ts from schema/v1/profile.schema.json. Do not edit by hand.

/** A published (flat) profile (SPEC §2). */
export interface Profile {
	$schema?: string;
	schemaVersion: SchemaVersion;
	id: ProfileId;
	/** hardware: a device's EQ engine. software: an app's EQ, selected by id (SPEC §2). */
	kind: 'hardware' | 'software';
	device: Device;
	/** Free label ("PEQ", "Graphic EQ"). Required when several profiles share a match (SPEC §3). */
	engine?: string;
	match?: Match;
	/** Number of slots. null = unbounded, software only (SPEC §2). */
	bandCount: number | null;
	band: Slot;
	/** Per-slot overrides of the band template, merged per key, replace (SPEC §5.2). */
	bands?: BandOverride[];
	rules?: Rule[];
	preamp: Preamp;
	/** Only "linked" in v1; "independent" is reserved (SPEC §9). */
	channels?: 'linked';
	meta: Meta;
}

/** A source file under data/, before the build flattens `extends` (SPEC §11). */
export interface AuthoringProfile {
	$schema?: string;
	schemaVersion?: SchemaVersion;
	id: ProfileId;
	/** hardware: a device's EQ engine. software: an app's EQ, selected by id (SPEC §2). */
	kind?: 'hardware' | 'software';
	device?: Device;
	/** Free label ("PEQ", "Graphic EQ"). Required when several profiles share a match (SPEC §3). */
	engine?: string;
	match?: Match;
	/** Number of slots. null = unbounded, software only (SPEC §2). */
	bandCount?: number | null;
	band?: Slot;
	/** Per-slot overrides of the band template, merged per key, replace (SPEC §5.2). */
	bands?: BandOverride[];
	rules?: Rule[];
	preamp?: Preamp;
	/** Only "linked" in v1; "independent" is reserved (SPEC §9). */
	channels?: 'linked';
	meta: AuthoringMeta;
	/** A base only: never published, needs no match or device (SPEC §11). */
	abstract?: boolean;
	/** Start from this profile and apply this file on top. match, device, meta and id are never inherited (SPEC §11). */
	extends?: ProfileId;
}

/** Minimum format version this profile needs: "1.<minor>" (SPEC §15). */
export type SchemaVersion = string;

/** Permanent public API. Conventionally <brand>-<model>[-<engine>] (SPEC §2). */
export type ProfileId = string;

export interface Device {
	brand: string;
	model: string;
	/** Marketing and regional names. Search only, never matching. */
	aliases?: string[];
	/** The profile stands for several products its match can't tell apart (a chipset family, a firmware scheme). Hardware only; default false (SPEC §2). */
	group?: boolean;
}

/** Lists are OR-ed; fields within one entry are AND-ed (SPEC §3). */
export interface Match {
	usb?: UsbMatch[];
	bluetooth?: BluetoothMatch[];
	firmware?: FirmwareRange;
}

/** Lowercase 4-digit hex string. */
export type UsbId = string;

/** vendorId plus productId and/or productName. Vendor-only matching is too broad (SPEC §3). */
export interface UsbMatch {
	vendorId: UsbId;
	productId?: UsbId;
	/** Compared exactly, case and whitespace included. */
	productName?: string;
}

/** name or namePrefix is required; serviceUuid alone is never sufficient (SPEC §3). */
export interface BluetoothMatch {
	name?: string;
	namePrefix?: string;
	serviceUuid?: string;
}

/** min inclusive, max exclusive, dotted-numeric order (SPEC §3). */
export interface FirmwareRange {
	min?: string;
	max?: string;
}

/** Allowed values of one numeric field: range, stepped range, set or locked (SPEC §4). */
export type Domain = RangeDomain | SteppedDomain | SetDomain | LockedDomain;

/** Closed interval [min, max]. */
export interface RangeDomain {
	min: number;
	max: number;
}

/** { k·step : k ∈ ℤ } ∩ [min, max], grid anchored at 0. min and max lie on the grid. */
export interface SteppedDomain {
	min: number;
	max: number;
	step: number;
}

/** Listed values: ascending, unique, non-empty. */
export interface SetDomain {
	values: number[];
}

/** Exactly one value; UIs render the field read-only. */
export interface LockedDomain {
	value: number;
}

/** Equalizer APO codes with RBJ cookbook semantics (SPEC §5.3), or a vendor-specific x-<name>. */
export type FilterType = 'PK' | 'LSC' | 'HSC' | 'LPQ' | 'HPQ' | 'BP' | 'NO' | 'AP' | `x-${string}`;

/** Allowed filter types, non-empty, in preference order. */
export type FilterTypes = FilterType[];

export interface SlotFields {
	/** Optional UI hint. */
	label?: string;
	types?: FilterTypes;
	freq?: Domain;
	q?: Domain;
	gain?: Domain;
	/** Conditional domains; per field, first match wins (SPEC §6). */
	variants?: Variant[];
}

/** Slot template. After merging with bands, every slot MUST define types, freq, q and gain (SPEC §5). */
export type Slot = SlotFields;

/** Overrides the template for one or more slots (SPEC §5.2). */
export interface BandOverride extends SlotFields {
	index: number | number[];
}

/** A conditional override of freq, q or gain. Never types (SPEC §6). */
export interface Variant {
	when: When;
	freq?: Domain;
	q?: Domain;
	gain?: Domain;
}

/** All conditions must hold. A condition on a null or missing field is false. */
export interface When {
	type?: TypeCondition;
	freq?: NumericCondition;
	q?: NumericCondition;
	gain?: NumericCondition;
}

export interface TypeCondition {
	eq?: FilterType;
	in?: FilterTypes;
}

/** Several comparisons in one object are AND-ed. */
export interface NumericCondition {
	eq?: number;
	gt?: number;
	gte?: number;
	lt?: number;
	lte?: number;
}

/** Cross-slot rules, a closed set in v1 (SPEC §7). */
export type Rule = AscendingFrequencyRule | MinSpacingRule;

/** On the completed slot array, freq[i] < freq[i+1] (<= when not strict). */
export interface AscendingFrequencyRule {
	type: 'ascendingFrequency';
	strict?: boolean;
}

/** Any two active filters are at least `octaves` apart. */
export interface MinSpacingRule {
	type: 'minSpacing';
	octaves: number;
}

/** manual: adjustable within gain. auto: the device computes its own headroom. none: no control. unknown: e.g. seeded data (SPEC §9). */
export type Preamp =
	| {
			mode: 'manual';
			gain: Domain;
	  }
	| {
			mode: 'auto' | 'none' | 'unknown';
	  };

export type GithubHandle = string;

/** Provenance of a claim (SPEC §10). */
export interface SourceFields {
	/** probe, vendor-docs, vendor-app and measurement count toward verification; handler-code and community don't. */
	kind: 'probe' | 'vendor-docs' | 'vendor-app' | 'measurement' | 'handler-code' | 'community';
	/** URL, citation, or for probe and measurement a path under evidence/. */
	ref: string;
	date: string;
	firmware?: string;
	by?: GithubHandle;
}

export interface Source extends SourceFields {
	/** Set by the build: id of the base this source was inherited from. Never counts toward status (SPEC §11). */
	via?: ProfileId;
}

/** replacedBy is required iff status is deprecated (SPEC §10). */
export interface MetaFields {
	status: 'draft' | 'community-verified' | 'maintainer-verified' | 'deprecated';
	replacedBy?: ProfileId;
	contributors?: GithubHandle[];
	notes?: string;
}

export interface Meta extends MetaFields {
	sources: Source[];
}

/** Provenance of a claim. `via` is set only by the build (SPEC §10). */
export type AuthoringSource = SourceFields;

export interface AuthoringMeta extends MetaFields {
	sources: AuthoringSource[];
}
